language: python
python:
  - "2.7"
  
  
install: 

  - sudo apt-get update
  - pip install -r requirements.txt
  - pip install coveralls

services:
  - sqlite3
  - python -m unittest discover
after_success:
  coveralls

