language: python
python:
  - "2.7"
  
  
install: 

  - sudo apt-get update
  - pip install -r requirements.txt
  - pip install coveralls

services:
  - sqlite3
script:
  - coverage run --omit=*/site-packages/*,*/tests/* -m unittest discover -s tests
after_success:
  coveralls
